services:
  proyect_db:
    image: postgres:16.8-alpine3.20
    container_name: proyect_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_EXTERNAL_PORT}:${POSTGRES_INTERNAL_PORT}"
    volumes:
      - postgres_data:${POSTGRES_DATA_PATH} # Usamos el volumen nombrado
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 3s
      timeout: 2s
      retries: 5
      start_period: 3s

volumes: # Definición del volumen nombrado
  postgres_data:
