-- Insertar datos en CATEGORIA
INSERT INTO CATEGORIA (DESCRIPCION, TIPO, ESTADO) VALUES
('Electrónica', 'PRODUCTO', 'ACTIVO'),
('Muebles', 'PRODUCTO', 'ACTIVO'),
('Servicios', 'SERVICIO', 'ACTIVO');

-- Insertar datos en ITEM
INSERT INTO ITEM (NOMBRE, DESCRIPCION, CATEGORIA_ID, TIPO, ESTADO) VALUES
('Computadora portátil', 'Portátil HP EliteBook x360 1040 G8', 1, 'PRODUCTO', 'ACTIVO'),
('Monitor', 'Monitor LG Ultrafine 27UL650-W', 1, 'PRODUCTO', 'ACTIVO'),
('Silla de oficina', 'Silla ergonómica Steelcase Gesture', 2, 'PRODUCTO', 'ACTIVO'),
('Servicio de reparación de computadoras', 'Servicio de reparación de computadoras portátiles y de escritorio', 3, 'SERVICIO', 'ACTIVO'),
('Servicio de limpieza de oficinas', 'Servicio de limpieza de oficinas a fondo', 3, 'SERVICIO', 'ACTIVO');

-- Insertar datos en PRODUCTOS
INSERT INTO PRODUCTOS (ITEM_ID, STOCK, PRECIO, COSTE) VALUES
(1, 10, 1200.00, 800.00),
(2, 5, 400.00, 250.00),
(3, 20, 300.00, 150.00);

-- Insertar datos en SERVICIO
INSERT INTO SERVICIO (ITEM_ID, PRECIO) VALUES
(4, 150.00),
(5, 100.00);

-- Insertar datos en AJUSTE_PRECIO
INSERT INTO AJUSTE_PRECIO (DESCRIPCION, APLICABLE_A, TIPO, VALOR, ESTADO) VALUES
('IVA (10%)', 'PRODUCTO', 'IMPUESTO', 10.00, 'ACTIVO'),
('Descuento por volumen (5%)', 'PRODUCTO', 'DESCUENTO', 5.00, 'ACTIVO');

-- Insertar datos en CLIENTE
INSERT INTO CLIENTE (DNI, RAZON_SOCIAL, ESTADO) VALUES
('V12345678', 'Distribuidora JJ C.A.', 'ACTIVO'),
('E98765432', 'Ana Rodríguez', 'ACTIVO');

-- Insertar datos en DIRECCION
INSERT INTO DIRECCION (PAIS, ESTADO, MUNICIPIO, PARROQUIA, SECTOR, CALLE, CASA) VALUES
('Venezuela', 'Lara', 'Iribarren', 'Juan de Villegas', 'Centro', 'Calle 20', '15-30'),
('Venezuela', 'Miranda', 'Sucre', 'Petare', 'La Urbina', 'Avenida Principal', 'Edf. 12, Apto. 3B');

-- Insertar datos en CLIENTE_DIRECCIONES
INSERT INTO CLIENTE_DIRECCIONES (CLIENTE_ID, DIRECCION_ID, ESTADO) VALUES
((SELECT ID FROM CLIENTE WHERE DNI = 'V12345678'), (SELECT ID FROM DIRECCION WHERE CALLE = 'Calle 20'), 'ACTIVO'),
((SELECT ID FROM CLIENTE WHERE DNI = 'E98765432'), (SELECT ID FROM DIRECCION WHERE CALLE = 'Avenida Principal'), 'ACTIVO');

-- Insertar datos en TELEFONO
INSERT INTO TELEFONO (CLIENTE_ID, PAIS, OPERADORA, NUMERO, ESTADO) VALUES
((SELECT ID FROM CLIENTE WHERE DNI = 'V12345678'), '58', 'Movistar', '0414-1234567', 'ACTIVO'),
((SELECT ID FROM CLIENTE WHERE DNI = 'E98765432'), '58', 'Digitel', '0412-9876543', 'ACTIVO');

-- Insertar datos en CORREO
INSERT INTO CORREO (CLIENTE_ID, DESCRIPCION, DOMINIO, ESTADO) VALUES
((SELECT ID FROM CLIENTE WHERE DNI = 'V12345678'), 'Correo Principal', 'distribuidorajj.com', 'ACTIVO'),
((SELECT ID FROM CLIENTE WHERE DNI = 'E98765432'), 'Correo Personal', 'anarodriguez.net', 'ACTIVO');

-- Insertar datos en ORDEN
INSERT INTO ORDEN (CLIENTE_ID, FECHA, ESTADO) VALUES
((SELECT ID FROM CLIENTE WHERE DNI = 'V12345678'), '2025-03-15', 'ACTIVO'),
((SELECT ID FROM CLIENTE WHERE DNI = 'E98765432'), '2025-03-18', 'ACTIVO');

-- Insertar datos en FACTURA (asegurándose de que ORDEN existe)
INSERT INTO FACTURA (ORDEN_ID, SERIE, NUMERO, FECHA, ESTADO) VALUES
((SELECT ID FROM ORDEN WHERE CLIENTE_ID = (SELECT ID FROM CLIENTE WHERE DNI = 'V12345678') AND FECHA = '2025-03-15'), 'A', '00001', '2025-03-15', 'ACTIVO'),
((SELECT ID FROM ORDEN WHERE CLIENTE_ID = (SELECT ID FROM CLIENTE WHERE DNI = 'E98765432') AND FECHA = '2025-03-18'), 'B', '00002', '2025-03-18', 'ACTIVO');

-- Insertar datos en DETALLES_ORDEN
INSERT INTO DETALLES_ORDEN (ORDEN_ID, ITEM_ID, CANTIDAD, SUBTOTAL, IMPUESTO_APLICADO, DESCUENTO_APLICADO) VALUES
((SELECT ID FROM ORDEN WHERE CLIENTE_ID = (SELECT ID FROM CLIENTE WHERE DNI = 'V12345678') AND FECHA = '2025-03-15'), (SELECT ID FROM ITEM WHERE NOMBRE = 'Computadora portátil'), 1, 1000.00, 100.00, 0.00),
((SELECT ID FROM ORDEN WHERE CLIENTE_ID = (SELECT ID FROM CLIENTE WHERE DNI = 'V12345678') AND FECHA = '2025-03-15'), (SELECT ID FROM ITEM WHERE NOMBRE = 'Monitor'), 2, 350.00, 70.00, 0.00),
((SELECT ID FROM ORDEN WHERE CLIENTE_ID = (SELECT ID FROM CLIENTE WHERE DNI = 'E98765432') AND FECHA = '2025-03-18'), (SELECT ID FROM ITEM WHERE NOMBRE = 'Silla de oficina'), 1, 250.00, 25.00, 12.50),
((SELECT ID FROM ORDEN WHERE CLIENTE_ID = (SELECT ID FROM CLIENTE WHERE DNI = 'E98765432') AND FECHA = '2025-03-18'), (SELECT ID FROM ITEM WHERE NOMBRE = 'Servicio de reparación de computadoras'), 1, 120.00, 12.00, 0.00);

-- Insertar datos en ITEM_AJUSTE (aplicando impuestos y descuentos a ítems)
INSERT INTO ITEM_AJUSTE (ITEM_ID, AJUSTE_PRECIO_ID) VALUES
((SELECT ID FROM ITEM WHERE NOMBRE = 'Computadora portátil'), (SELECT ID FROM AJUSTE_PRECIO WHERE DESCRIPCION = 'IVA (10%)')),
((SELECT ID FROM ITEM WHERE NOMBRE = 'Monitor'), (SELECT ID FROM AJUSTE_PRECIO WHERE DESCRIPCION = 'IVA (10%)')),
((SELECT ID FROM ITEM WHERE NOMBRE = 'Silla de oficina'), (SELECT ID FROM AJUSTE_PRECIO WHERE DESCRIPCION = 'IVA (10%)')),
((SELECT ID FROM ITEM WHERE NOMBRE = 'Computadora portátil'), (SELECT ID FROM AJUSTE_PRECIO WHERE DESCRIPCION = 'Descuento por volumen (5%)')),
((SELECT ID FROM ITEM WHERE NOMBRE = 'Silla de oficina'), (SELECT ID FROM AJUSTE_PRECIO WHERE DESCRIPCION = 'Descuento por volumen (5%)'));